### ISSUE TITLE
cmake looks for mstore but binaries aren't linked with it

### ISSUE THREAD

**Issue by yurivict** [awvwgk/simple-dftd3#11]
mstore's executables also aren't used.
Is this an unnecessary check in cmake?

**Comment by awvwgk** [comment]
`mstore` is not supposed to be linked in any final library. It only serves the data required for running the unit tests and is linked with the test driver:

https://github.com/awvwgk/simple-dftd3/blob/a9e8051c186e07de323620a2b42c134dc4a4faf1/test/unit/CMakeLists.txt#L37-L46

Think of it as development or build dependency rather than a proper dependency. However, unless CMake can find an external dependency, it will build `mstore` on demand and also install it, because this behavior turns out be quite hard to disable with CMake.

**Comment by yurivict** [comment]
Thank you.
